"""
Django settings for NBiblioteca project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-key'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del proyecto
    'apps.management',
    'apps.alumnos',
    'apps.libros',
    'apps.prestamos',
    'apps.multas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NBiblioteca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NBiblioteca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ══════════════════════════════════════════════════════════
# JAZZMIN — Admin UI (solo Users y Groups)
# ══════════════════════════════════════════════════════════
JAZZMIN_SETTINGS = {
    # ── Top menu (barra superior) ──────────────────────────
    "topmenu_links": [
        {"name": "Ir a la Biblioteca", "url": "/", "new_window": False, "icon": "fas fa-home"},
    ],
    # ── Identidad ──────────────────────────────────────────
    "site_title":        "Biblioteca UNICAES",
    "site_header":       "Biblioteca UNICAES",
    "site_brand":        "Admin",
    "welcome_sign":      "Panel de administración",
    "copyright":         "UNICAES",

    # ── Logo / favicon ─────────────────────────────────────
    "site_logo":         "img/UNICAES_Logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon":         "img/UNICAES_Logo.png",

    # ── Solo muestra auth (Users y Groups) ─────────────────
    "hide_apps":  [],
    "hide_models": [],
    "order_with_respect_to": ["auth"],

    # ── Menú lateral ───────────────────────────────────────
    "show_sidebar":          True,
    "navigation_expanded":   True,
    "hide_apps":             [],

    # ── Búsqueda en topbar ─────────────────────────────────
    "search_model": ["auth.user"],

    # ── Links de usuario ───────────────────────────────────
    "usermenu_links": [
        {"name": "Ir a la Biblioteca", "url": "/", "icon": "fas fa-home"},
    ],

    # ── Iconos por modelo ──────────────────────────────────
    "icons": {
        "auth":            "fas fa-users-cog",
        "auth.user":       "fas fa-user",
        "auth.Group":      "fas fa-users",
    },
    "default_icon_parents":  "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── UI ─────────────────────────────────────────────────
    "related_modal_active":    True,
    "custom_css":              None,
    "custom_js":               None,
    "use_google_fonts_cdn":    False,
    "show_ui_builder":         False,
    "changeform_format":       "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":  False,
    "footer_small_text":  False,
    "body_small_text":    False,
    "brand_small_text":   False,
    "brand_colour":       "navbar-white",
    "accent":             "accent-primary",
    "navbar":             "navbar-white navbar-light",
    "no_navbar_border":   False,
    "navbar_fixed":       True,
    "layout_boxed":       False,
    "footer_fixed":       False,
    "sidebar_fixed":      True,
    "sidebar":            "sidebar-light-primary",
    "sidebar_nav_small_text":    False,
    "sidebar_disable_expand":    False,
    "sidebar_nav_child_indent":  True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style":  False,
    "sidebar_nav_flat_style":    False,
    "theme":              "default",
    "dark_mode_theme":    None,
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}
